version: '3.7'

services:
  app:
    container_name: ummul-quran-frontend
    image: ummul-quran-frontend
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "80:80"
